
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX ns2: <https://data.vlaanderen.be/ns/adres#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dbpo: <http://dbpedia.org/ontology/>
PREFIX schema: <http://schema.org/>

INSERT {
  GRAPH <http://sem.jsz4n.dev/lblod>{
    ?s1 dbpo:postalCode ?code.
    ?s1 dbpo:City ?s2.
  }
} WHERE {
    GRAPH <http://sem.jsz4n.dev/lblod>{
        ?s1 a locn:Address; ns2:gemeentenaam ?city; locn:fullAddress ?fad.
        ?s2 a dbpo:City; ns2:gemeentenaam ?city; dbpo:postalCode ?code.
#    	BIND ( STR(STRBEFORE(STRAFTER(STR(?fad), ", "), " ")) as ?code)
  }
}
